spring:
  # Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/beersound
    username: beersound
    password: bs-secret

  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create-drop
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Fixes: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest

auth:
  secret: beersound-secret
  issuer: beersound-backend
  token_lifetime: 43200
  header_name: BS-Token
  spotify_header_name: Spotify-Token

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG